### ISSUE TITLE
Max Range Is incorrect

### ISSUE THREAD

**Issue by Gaz492** [claws/dump1090-exporter#15]
When comparing the dump1090 webUI to the info in grafana the max range is totally incorrect
![firefox_2018-12-09_20-21-45](https://user-images.githubusercontent.com/840990/49702483-6f21a980-fbf0-11e8-8463-b82cfca96af6.png)

**Comment by claws** [comment]
In the screenshot you provided the maximum range I see on the webUI is 53nm which is 98km. Seems right to me.

**Comment by claws** [comment]
I'll assume from the lack of feedback that this issue was just a misunderstanding or a mis-reading of Nautical Miles in the WebUI versus Kilometres in the dump1090 Grafana UI. 

Feel free to re-open if you think I have misunderstood your problem.
