### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by techfixpros** [claws/dump1090-exporter#16]
I am receiving the following error when attempting to start dump1090exporter on my piaware unit:
```
pi@piaware:~ $ dump1090exporter \
>   --url=http://192.168.1.211:8080 \
>   --port=9105 \
>   --latitude=hidden \
>   --longitude=-hidden \
>   --debug
Traceback (most recent call last):
  File "/usr/local/bin/dump1090exporter", line 7, in <module>
    from dump1090exporter.__main__ import main
  File "/usr/local/lib/python3.5/dist-packages/dump1090exporter/__init__.py", line 2, in <module>
    from .exporter import Dump1090Exporter
  File "/usr/local/lib/python3.5/dist-packages/dump1090exporter/exporter.py", line 61
    f"{base_url}/data/receiver.json",
                                   ^
SyntaxError: invalid syntax
```
When run as a docker container the instance will restart every few seconds. On github, the only issues pertaining to python state it requires >=3.5, of which I am running 3.5. I have tried the variables in " " and receive the same error. I even get the same error when running dump1090exporter -h.
Official PiAware 3.7.2 image
Python 3.5

**Comment by claws** [comment]
The package actually requires Python 3.6.

The error is related to the use of syntax that was introduced in Python 3.6, the f-string syntax for string substitution. 

I did a quick checked of the ``Readme.rst`` file (the Install section) and the ``setup.py`` file and both state that the package requires Python 3.6.

Maybe I missed updating a reference to the minimum Python version. If you tell me where you found the reference to the erroneous minimum Python version of 3.5+ I can fix it to state 3.6+.

**Comment by techfixpros** [comment]
Sorry, I see it now, don't know how I missed that. I looked in the issues section and issue 8 `https://github.com/claws/dump1090-exporter/issues/8` stated 3.5, but was from 2017.

But for reference, is it safe to install python 3.6 or higher on an official piaware image?

**Comment by afk11** [comment]
@techfixpros I had this question, but was able to compile 3.6 from source without messing with the systems python per the following: https://gist.github.com/dschep/24aa61672a2092246eaca2824400d37f
