### ISSUE TITLE
Building Docker image fails

### ISSUE THREAD

**Issue by marcelstoer** [claws/dump1090-exporter#18]
Building the Docker image (on Raspberry Pi and elsewhere) fails at 

```
COPY ./dist/dump1090exporter-*-py3-none-any.whl /tmp/
```

as there is no `/dist` folder. Where should this come from i.e. when is it created?

**Comment by claws** [comment]
Prior to running the Docker build you need to build the ``dump1090export`` Python package. This can be done by running the ``make dist`` rule. However, you will need at least the ``wheel`` package installed first. I normally follow a process like this to install the development requirements:
```console
$ python3 -m venv venv --prompt exp
$ source venv/bin/activate
(exp) $ pip install pip -U
(exp) $ pip install -r requirements.dev.txt
(exp) $ make dist
```

**Comment by marcelstoer** [comment]
Great! Thanks for the quick replay, I appreciate that. Could you maybe add this information to the README?

I built the Python package on the Mac. Then I used [Docker buildx](https://frightanic.com/computers/docker-buildx-the-best-thing-since-sliced-bread/) to create multi-arch images that also support the Raspberry Pi: https://hub.docker.com/r/marcelstoer/dump1090-exporter

Thanks for this probject.
