### ISSUE TITLE
Open JSON files locally, as files instead of via http

### ISSUE THREAD

**Issue by SaturnusDJ** [claws/dump1090-exporter#19]
Currently you have to got the Dump1090 webserver running, so that the files are available via http. Can support be added for reading the files from the Linux filesystem?

`dump1090exporter --url "/home/dump1090/" ...` 😁

**Comment by claws** [comment]
Updated (in #21) the repo to support reading the dump1090 status from files as requested. 
``dump1090exporter`` v20.0.0 has been released to PyPI. 
A new Docker container image has been pushed to ``clawsicus/dump1090exporter`` on DockerHub.

**Comment by SaturnusDJ** [comment]
That's absolutely awesome. Got it working with own Docker images but using yours as example.

Reason for asking was that the RPi ADS-B receiver runs (own) Docker containers for Dump1090 and MLAT feeders and all other stuff is done by a stronger server. So the Dump1090 JSONs are written to an NFS hosted by that server that also does databasing, stats, etc.

Thanks so much.
