### ISSUE TITLE
unable to pull distance/range stats if dump1090 is started after dump1090exporter

### ISSUE THREAD

**Issue by jkstay** [claws/dump1090-exporter#29]
Receiver position in receiver.json is only pulled once during dump1090exporter startup. If failed, origin would be null (unless explicitly set in CLI args) and hence all distance/range calculations would fail until dump1090exporter is restarted.

This is problematic because it creates a race condition on system startup.

This might also lead to incorrect distances in the edge case of changed receiver position without restarting dump1090exporter.

**Comment by claws** [comment]
Fixed by #30
