### ISSUE TITLE
Possible issue with PiAware v5

### ISSUE THREAD

**Issue by beercity** [claws/dump1090-exporter#31]
I upgraded my RPi to PiAware v5 and I am getting errors in the logs about not being able access aircraft.json and stats.json. I cannot access either of these in the browser either, I get 404 error.

**Comment by tkyocum** [comment]
Hi,

This still works on piaware 5 - check your syntax and make sure you're pointing `--resource-path` at `/var/run/dump1090-fa` which is where those two JSON files live.

**Comment by claws** [comment]
This sounds like a configuration issue as noted by @tkyocum. Re-open if you think the issue is actually in this project.
