### ISSUE TITLE
Explicit Python version

### ISSUE THREAD

**Issue by hbokh** [claws/dump1090-exporter#8]
Hi!

I'm running into this error:

```
Installing collected packages: dump1090exporter, aiohttp, aioprometheus, chardet, multidict, async-timeout, yarl, quantile-python
  Running setup.py install for dump1090exporter
      File "/home/pi/dump1090exporter/lib/python3.4/site-packages/dump1090exporter/exporter.py", line 52
        async def fetch(url: str,
                ^
    SyntaxError: invalid syntax
```

On Raspbian Jessie the default Python is v3.4.  
It seems to me this script specifically needs Python 3.5 or higher, judging this explanation of the error mentioned above: https://raspberrypi.stackexchange.com/questions/58416/python3-flagging-async-def-as-invalid-syntax

PS Works fine on macOS 10.12.5 and Python 3.6.  
Except I had to comment this line: https://github.com/claws/dump1090-exporter/blob/master/dump1090exporter/exporter.py#L13.  
Probable cause: "[Looks like in version 2.0.0 aiohttp dropped aiohttp.errors](https://github.com/maas/python-libmaas/issues/95#issue-215647756)".

**Comment by claws** [comment]
Thanks for leaving feedback and bring this to my attention. 

I've updated the README to explicitly state that Python3.5+ is required and I have pinned the aiohttp library to the supported version. V1 and V2 of aiohttp introduced significant changes that I have not yet had time to accommodate for in the aioprometheus library this project uses.
